export const colors = {
  mainPalette: {
    red: "#D72B2B",
    orange: "#ffa52f",
    white: "rgba(255,255,255,0.75)",
    black: "#000000",
  },
  index: {
    background: "#f5f5f5",
    emptyText: "#666",
  },
  birdCard: {
    background: "#FFFFFF",
    subtitle: "#666666",
    tagText: "#FFFFFF",
    moreTagBackground: "#EEEEEE",
    actionEdit: "#666666",
    actionDelete: "#E63946",
  },
  birdEmpty: {
    text: "#686868",
    buttonBackground: "#E53935",
    buttonText: "#FFFFFF",
  },
  habitatsCard: {
    text: "#333333",
    selected: "#f3a6a4",
  },
  pagination: {
    indicatorText: "#333333",
    buttonDisabled: "#f3a6a4",
  },
  searchInput: {
    icon: "#999999",
    background: "#DADADA",
  },
  updateBird: {
    primary: "#D94040",
    primaryDark: "#296811",
    background: "#F5F5F5",
    imageBackground: "#E0E0E0",
    imagePlaceholderBackground: "#EEEEEE",
    changeImageButtonBackground: "rgba(0,0,0,0.55)",
    changeImageTextColor: "#FFFFFF",
    saveTextColor: "#FFFFFF",
    surface: "#FFFFFF",
    border: "#E0E0E0",
    textPrimary: "#1A1A1A",
    textSecondary: "#757575",
    textPlaceholder: "#BDBDBD",
    chipDefault: "#EEEEEE",
    chipDefaultText: "#424242",
    chipSelected: "#D94040",
    chipSelectedText: "#FFFFFF",
    cancel: "#FFFFFF",
    cancelBorder: "#CCCCCC",
    cancelText: "#424242",
  },
  addBird: {
    primary: "#D94040",
    background: "#F5F5F5",
    imageBackground: "#E0E0E0",
    imagePlaceholderBackground: "#EEEEEE",
    changeImageButtonBackground: "rgba(0,0,0,0.55)",
    changeImageTextColor: "#FFFFFF",
    saveTextColor: "#FFFFFF",
    surface: "#FFFFFF",
    border: "#E0E0E0",
    textPrimary: "#1A1A1A",
    textSecondary: "#757575",
    textPlaceholder: "#BDBDBD",
    chipDefault: "#EEEEEE",
    chipDefaultText: "#424242",
    chipSelected: "#D94040",
    chipSelectedText: "#FFFFFF",
    cancel: "#FFFFFF",
    cancelBorder: "#CCCCCC",
    cancelText: "#424242",
  },
  aboutMe: {
    background: "#F5F5F5",
    descriptionColor: "#333",
  },
};
